# Generated by Django 5.1.3 on 2024-12-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='dod',
            new_name='date_of_death',
        ),
    ]
